import Head from 'next/head';
import Layout from '../components/layout';
import Hero from '../components/home/hero';
import dynamic from 'next/dynamic';

// ⭐ 서버에서는 import 자체를 하지 않도록 동적 임포트 + ssr:false
const Anime = dynamic(() => import('../components/home/anime'), {
  ssr: false,
  loading: () => <div style={{ height: 240 }} />, // 선택: 로딩 자리
});

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>센텀준호</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="flex flex-col items-center justify-center min-h-screen text-gray-600 body-font">
        <div className="container flex flex-col items-center px-5 py-24 mx-auto md:flex-row">
          <Hero />
        </div>
      </section>
    </Layout>
  );
}
