import Head from 'next/head';
import Link from 'next/link';
import Layout from '../components/layout';
import Hero from '../components/home/hero';
import dynamic from 'next/dynamic';

// ⭐ 서버에서는 import 자체를 하지 않도록 동적 임포트 + ssr:false
const Anime = dynamic(() => import('../components/home/anime'), {
  ssr: false,
  loading: () => <div style={{ height: 240 }} />, // 선택: 로딩 자리
});

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>센텀준호</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="flex flex-col items-center justify-center min-h-screen text-gray-600 body-font">
        <div className="container flex flex-col items-center px-5 py-24 mx-auto md:flex-row">
          <Hero />
        </div>
      </section>

      {/* Todo App Demo Section */}
      <section className="flex flex-col items-center justify-center px-6 py-12 bg-slate-50 dark:bg-slate-900/50">
        <div className="container mx-auto max-w-2xl">
          <div className="flex flex-col items-center gap-4 p-6 rounded-xl border border-slate-200 bg-white dark:border-slate-700 dark:bg-slate-800 shadow-sm">
            <h2 className="text-xl font-semibold text-slate-900 dark:text-white">
              Todo App Demo
            </h2>
            <p className="text-sm text-center text-slate-600 dark:text-slate-400">
              A simple Next.js todo application demo showcasing task management features.
            </p>
            <Link
              href="https://next-joon-todo-deploy.vercel.app/"
              target="_blank"
              rel="noopener noreferrer"
              className="
                inline-flex items-center justify-center
                rounded-lg bg-gradient-to-r from-cyan-500 to-indigo-500
                px-4 py-2 text-sm font-semibold text-white
                transition hover:opacity-90 shadow-sm
              "
            >
              Go to Todo App
            </Link>
          </div>
        </div>
      </section>
    </Layout>
  );
}
